# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "Archipelago.MultiClient.Net"; version = "6.5.0"; sha256 = "14xwzaw7c51syw6zjxfl06pq8grfa26xbsiahvl73m4xgdfz3psd"; })
]
